In [22]:
import numpy as np
a = np.array([[0,np.NaN, 2],[3,4,5]])
a

array([[ 0., nan,  2.],
       [ 3.,  4.,  5.]])

In [36]:
np.isnan(a)

array([[False,  True, False],
       [False, False, False]])

In [26]:
#Remove cols with NaN
a[:,~np.isnan(a).any(axis=0)]

array([[0., 2.],
       [3., 5.]])

In [33]:
a[:,[0,2]]

array([[0., 2.],
       [3., 5.]])

In [25]:
#Remove rows with NaN
a[~np.isnan(a).any(axis=1),:]

array([[3., 4., 5.]])

In [29]:
import pandas as pd
df=pd.DataFrame(a)
df

0    1    2
0  0.0  NaN  2.0
1  3.0  4.0  5.0

In [30]:
df[:,~np.isnan(df).any(axis=0)]

KeyError: (slice(None, None, None), 0     True
1    False
2     True
dtype: bool)